name: status_saver
description: A modern WhatsApp Status Saver for Android 14+
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🔥 مهم جدًا لاختيار مجلد الحالات (SAF)
  file_picker: ^6.1.1

  # 🔐 للأذونات (لو احتجتها لاحقًا)
  permission_handler: ^11.3.1

  # 📤 مشاركة الحالات
  share_plus: ^7.2.2

  # 📁 إدارة المسارات
  path_provider: ^2.1.3

  # 💾 حفظ المسار (مهم)
  shared_preferences: ^2.2.2

  # 🎬 تشغيل الفيديو داخل التطبيق
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
